apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: karpenter-servicemonitor
  namespace: monitoring
  labels:
    app.kubernetes.io/name: karpenter
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: karpenter
  namespaceSelector:
    matchNames:
      - karpenter
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 10s
      scrapeTimeout: 5s
