apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-nodepool
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/Sadik00789/Scale-To-Zero-Fleet"
    targetRevision: HEAD
    path: k8s
    directory:
      include: "karpenter-nodepool.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
